'use strict';
/** Sunucu-otoriteli 8-top motoru. Sabit zaman adımıyla top/top ve bant çarpışmalarını simüle eder. */
const C={W:900,H:450,L:58,R:842,T:58,B:392,r:10.5,pocketR:22,ballRestitution:.965,cushionRestitution:.89,rollingDecel:34,stopSpeed:2.2,maxShot:1080,dt:1/240,maxSteps:240*28};
const pockets=()=>[{x:C.L,y:C.T},{x:(C.L+C.R)/2,y:C.T-4},{x:C.R,y:C.T},{x:C.L,y:C.B},{x:(C.L+C.R)/2,y:C.B+4},{x:C.R,y:C.B}];
function rack(){const balls=[{id:'cue',n:0,type:'cue',x:245,y:225,vx:0,vy:0,potted:false}];const order=[1,9,2,10,8,3,11,4,12,5,6,13,7,14,15];let k=0;for(let row=0;row<5;row++)for(let j=0;j<=row;j++){const n=order[k++];balls.push({id:String(n),n,type:n===8?'eight':n<8?'solid':'stripe',x:610+row*18.8,y:225+(j-row/2)*21.5,vx:0,vy:0,potted:false});}return balls;}
function init(){return{balls:rack(),turn:0,status:'playing',winner:null,groups:[null,null],shots:0,score:[0,0],lastShot:null};}
function pocketOrRail(st,b,shot){for(const p of pockets()){const dx=p.x-b.x,dy=p.y-b.y,d=Math.hypot(dx,dy);if(d<C.pocketR-2){b.potted=true;b.vx=b.vy=0;shot.potted.push(b.id);return;}if(d<C.pocketR+15&&d>0){b.vx+=dx/d*5;b.vy+=dy/d*5;}}let rail=false;if(b.x<C.L+C.r){b.x=C.L+C.r;b.vx=Math.abs(b.vx)*C.cushionRestitution;rail=true;}else if(b.x>C.R-C.r){b.x=C.R-C.r;b.vx=-Math.abs(b.vx)*C.cushionRestitution;rail=true;}if(b.y<C.T+C.r){b.y=C.T+C.r;b.vy=Math.abs(b.vy)*C.cushionRestitution;rail=true;}else if(b.y>C.B-C.r){b.y=C.B-C.r;b.vy=-Math.abs(b.vy)*C.cushionRestitution;rail=true;}if(rail&&shot.firstHit)shot.railAfterContact=true;}
function collide(st,a,b,shot){if(a.potted||b.potted)return;const dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy),min=C.r*2;if(!d||d>=min)return;const nx=dx/d,ny=dy/d,over=min-d;a.x-=nx*over/2;a.y-=ny*over/2;b.x+=nx*over/2;b.y+=ny*over/2;const rel=(b.vx-a.vx)*nx+(b.vy-a.vy)*ny;if(rel>=0)return;const impulse=-(1+C.ballRestitution)*rel/2;a.vx-=impulse*nx;a.vy-=impulse*ny;b.vx+=impulse*nx;b.vy+=impulse*ny;if(!shot.firstHit&&(a.id==='cue'||b.id==='cue'))shot.firstHit=a.id==='cue'?b.id:a.id;}
function step(st,shot){const live=st.balls.filter(b=>!b.potted);for(const b of live){b.x+=b.vx*C.dt;b.y+=b.vy*C.dt;const speed=Math.hypot(b.vx,b.vy);if(speed){const next=Math.max(0,speed-C.rollingDecel*C.dt),k=next/speed;b.vx*=k;b.vy*=k;if(next<C.stopSpeed)b.vx=b.vy=0;}pocketOrRail(st,b,shot);}for(let pass=0;pass<2;pass++)for(let i=0;i<live.length;i++)for(let j=i+1;j<live.length;j++)collide(st,live[i],live[j],shot);return live.some(b=>Math.hypot(b.vx,b.vy)>=C.stopSpeed);}
function remaining(st,type){return st.balls.some(b=>!b.potted&&b.type===type);}
function shoot(st,seat,angle,power){if(!st||st.status!=='playing')return{ok:false,reason:'finished'};if(seat!==st.turn)return{ok:false,reason:'not_your_turn'};angle=Number(angle);power=Number(power);if(!Number.isFinite(angle)||!Number.isFinite(power)||power<=0||power>1)return{ok:false,reason:'bad_shot'};const cue=st.balls.find(b=>b.id==='cue');if(!cue||cue.potted)return{ok:false,reason:'cue_unavailable'};const shot={seat,firstHit:null,railAfterContact:false,potted:[],foul:false};const speed=(.18+.82*power)*C.maxShot;cue.vx=Math.cos(angle)*speed;cue.vy=Math.sin(angle)*speed;let moving=true,steps=0;while(moving&&steps++<C.maxSteps)moving=step(st,shot);const first=st.balls.find(b=>b.id===shot.firstHit),group=st.groups[seat],scratch=shot.potted.includes('cue');shot.foul=scratch||!first||!!(group&&first.type!==group&&!(first.id==='8'&&!remaining(st,group)))||(!shot.railAfterContact&&!shot.potted.length);const colors=shot.potted.map(id=>st.balls.find(b=>b.id===id)).filter(b=>b&&(b.type==='solid'||b.type==='stripe'));if(!st.groups[0]&&colors.length){st.groups[seat]=colors[0].type;st.groups[1-seat]=colors[0].type==='solid'?'stripe':'solid';}
const eight=shot.potted.includes('8');if(eight){const legal=group&&!remaining(st,group)&&!shot.foul;st.status='finished';st.winner=legal?seat:1-seat;}else{const legalPocket=colors.some(b=>!group||b.type===group);if(shot.foul||!legalPocket)st.turn=1-seat;}if(scratch){cue.potted=false;cue.x=245;cue.y=225;cue.vx=cue.vy=0;}st.shots++;st.score=st.groups[0]?[7-st.balls.filter(b=>!b.potted&&b.type===st.groups[0]).length,7-st.balls.filter(b=>!b.potted&&b.type===st.groups[1]).length]:[0,0];st.lastShot=shot;return{ok:true,shot,state:st,winner:st.winner};}
module.exports={init,shoot,constants:C};
