'use strict';
// Turkish draughts: men move orthogonally, capture orthogonally; kings slide
// any distance. Captures are compulsory and the longest capture is required.
const D=[[ -1,0],[1,0],[0,-1],[0,1]];const inside=(r,c)=>r>=0&&r<8&&c>=0&&c<8;
function init(){const b=Array.from({length:8},()=>Array(8).fill(null));for(let c=0;c<8;c++){b[1][c]='b';b[2][c]='b';b[5][c]='w';b[6][c]='w'}return{board:b,turn:'w',status:'playing',captures:{w:0,b:0},winner:null,history:[]}}
function dirs(p){return p===p.toUpperCase()?D:D.filter(x=>p.toLowerCase()==='w'?x[0]<0:x[0]>0||x[1]!==0)}
function capturesFor(st,r,c){const p=st.board[r]?.[c],col=p?.toLowerCase();if(!p||col!==st.turn)return[];const out=[];for(const [dr,dc] of dirs(p)){let er=r+dr,ec=c+dc;if(!inside(er,ec))continue;if(p===p.toUpperCase()){while(inside(er,ec)&&!st.board[er][ec]){er+=dr;ec+=dc}if(!inside(er,ec)||!st.board[er][ec]||st.board[er][ec].toLowerCase()===col)continue;let lr=er+dr,lc=ec+dc;while(inside(lr,lc)&&!st.board[lr][lc]){out.push({from:[r,c],to:[lr,lc],captures:[[er,ec]]});lr+=dr;lc+=dc}}else{const lr=r+2*dr,lc=c+2*dc;if(inside(lr,lc)&&st.board[er][ec]&&st.board[er][ec].toLowerCase()!==col&&!st.board[lr][lc])out.push({from:[r,c],to:[lr,lc],captures:[[er,ec]]})}}return out}
function allCaptures(st){let a=[];for(let r=0;r<8;r++)for(let c=0;c<8;c++)a.push(...capturesFor(st,r,c));return a}
function allMoves(st){const caps=allCaptures(st);if(caps.length){const n=Math.max(...caps.map(x=>x.captures.length));return caps.filter(x=>x.captures.length===n)}let a=[];for(let r=0;r<8;r++)for(let c=0;c<8;c++){const p=st.board[r][c];if(!p||p.toLowerCase()!==st.turn)continue;for(const[dr,dc]of dirs(p)){let nr=r+dr,nc=c+dc;if(p===p.toUpperCase())while(inside(nr,nc)&&!st.board[nr][nc]){a.push({from:[r,c],to:[nr,nc],captures:[]});nr+=dr;nc+=dc}else if(inside(nr,nc)&&!st.board[nr][nc])a.push({from:[r,c],to:[nr,nc],captures:[]})}}return a}
function play(st,seat,from,to){const col=seat===0?'w':'b';if(st.status!=='playing')return{ok:false,reason:'finished'};if(col!==st.turn)return{ok:false,reason:'not_your_turn'};const m=allMoves(st).find(x=>x.from[0]===from[0]&&x.from[1]===from[1]&&x.to[0]===to[0]&&x.to[1]===to[1]);if(!m)return{ok:false,reason:allCaptures(st).length?'must_capture':'illegal_move'};const p=st.board[from[0]][from[1]];st.board[from[0]][from[1]]=null;st.board[to[0]][to[1]]=p;for(const[r,c]of m.captures){st.board[r][c]=null;st.captures[col]++}if(p==='w'&&to[0]===0)st.board[to[0]][to[1]]='W';if(p==='b'&&to[0]===7)st.board[to[0]][to[1]]='B';st.history.push(m);const other=col==='w'?'b':'w';if(!st.board.some(row=>row.some(x=>x?.toLowerCase()===other))||!allMoves({...st,turn:other}).length){st.status='finished';st.winner=seat}else st.turn=other;return{ok:true,move:m,winner:st.winner}}
module.exports={init,allMoves,allCaptures,play};
